curl -X POST https://www.strava.com/oauth/token \
	-F client_id=153027 \
	-F client_secret=7718cee1f5038eede7eac4b7bf2a4b0cdf120447 \
	-F code=5c22b789b41cbb86fef279fc3abcc30db94dd69 \
	-F grant_type=authorization_code

###

POST https://www.strava.com/oauth/token?client_id=153027&client_secret=7718cee1f5038eede7eac4b7bf2a4b0cdf120447&code=5c22b789b41cbb86fef279fc3abcc30db94dd69&grant_type=authorization_code
Accept: application/json

###

GET https://www.strava.com/api/v3/athlete
Authorization: Bearer 41627d3473e39f4a0017e111b2ee2ad2750778a8